# Generated by Django 3.1 on 2022-04-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
