# Generated by Django 3.1 on 2022-04-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20220412_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст к фотографии'),
        ),
    ]
