# Generated by Django 3.1 on 2022-04-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_feature_html_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='html_form_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Имя для HTML формы'),
        ),
    ]
