# Generated by Django 3.1 on 2022-04-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotel_html_form_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='html_form_name',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('Гостиница', 'hotel'), ('Мотель', 'motel'), ('Апартаменты', 'apartments')], max_length=25, verbose_name='Тип жилья'),
        ),
    ]
