# Generated by Django 3.1 on 2022-04-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Причина')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Причина',
                'verbose_name_plural': 'Причины',
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reason_recommendation', to='home.reason', verbose_name='Причина'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='recommendation',
            order_with_respect_to='reason',
        ),
    ]
