# Generated by Django 3.1 on 2022-04-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220407_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='css_class',
            field=models.CharField(default='standart', max_length=50, verbose_name='CSS класс'),
        ),
    ]
