# Generated by Django 3.1 on 2022-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_recommendation_css_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='css_class',
        ),
        migrations.AddField(
            model_name='reason',
            name='css_class',
            field=models.CharField(default='standart', max_length=50, verbose_name='CSS класс'),
        ),
    ]
