# Generated by Django 3.1 on 2022-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220408_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Дата прибытия')),
                ('departure_date', models.DateField(verbose_name='Дата отъезда')),
                ('number_of_adults', models.IntegerField(verbose_name='Количество взрослых')),
                ('number_of_children', models.IntegerField(verbose_name='Количество детей')),
            ],
            options={
                'verbose_name': 'Модель для формы поиска',
                'verbose_name_plural': 'Модели для формы поиска',
            },
        ),
    ]
