# Generated by Django 3.1 on 2022-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bookformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookformmodel',
            name='number_of_adults',
            field=models.PositiveIntegerField(verbose_name='Число взрослых'),
        ),
        migrations.AlterField(
            model_name='bookformmodel',
            name='number_of_children',
            field=models.PositiveIntegerField(verbose_name='Число детей'),
        ),
    ]
