# Generated by Django 3.1 on 2022-04-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_reason_title_second_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='title_second_line',
        ),
    ]
